config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :products, only: %i[index show] do
    resource :payment, only: :create do
      collection do
        get :success
        get :cancel
        post :checkout_session
      end
    end
  end

  resources :cards

  namespace :webhooks do
    namespace :payment_methods do
      resource :stripe, only: :create
    end
  end

  root "products#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

   def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment_history.rb
class PaymentHistory < ApplicationRecord
  belongs_to :user

  enum status: { succeeded: 'succeeded', failed: 'failed', refunded: 'refunded' }


  def self.ransackable_attributes(auth_object = nil)
    ["application_fee", "created_at", "id", "id_value", "payment_intent_id", "status", "total_amount", "transfer_amount", "updated_at", "user_id"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	after_create_commit :create_stripe_customer

	def create_stripe_customer
		update_column(:stripe_customer_id, ::PaymentMethods::Stripe::CustomerService.call(:create_customer, self)[:id]) 
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

	def current_user
		User.first
	end

	private

	def record_not_found
		render file: "#{Rails.root}/public/404.html", layout: true, status: :not_found
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_stripe_customer_id

  def new
  end

  def create
    create_card_token!
    create_card!

    flash[:success] = "Card added successfully!"
    redirect_to  CGI.parse(URI(request.referer).query)["return_url"]&.first || root_path
  rescue StandardError => e
    flash[:error] = e.message
    redirect_to new_card_path
  end

  def destroy
    card_id = params[:id]
    response = PaymentMethods::Stripe::CardService.call(:delete_card, @stripe_customer_id, card_id)

    if response[:error]
      flash[:error] = response[:error]
    else
      flash[:success] = "Card deleted successfully"
    end
    redirect_back(fallback_location: root_path)
  end

  def make_default
    card_id = params[:id]
    response = StripeService.call(:make_default_card, @stripe_customer_id, card_id)
    return render json: { error: response[:error] }, status: :unprocessable_entity if response[:error].present?

    render json: { data: response.as_json, message: 'Set default successfully.', status: :ok }
  end

  private

  def set_stripe_customer_id
    current_user.create_stripe_customer if current_user.stripe_customer_id.nil?
    @stripe_customer_id = current_user.stripe_customer_id
  end

  def create_card_token!
    @card_token = PaymentMethods::Stripe::CardService.call(:create_card_token, params[:card_number], params[:exp_month], params[:exp_year], params[:cvc])
    raise @card_token[:error] if @card_token[:error]
  end

  def create_card!
    @card = PaymentMethods::Stripe::CardService.call(:create_card, @stripe_customer_id, @card_token[:id])
    raise @card[:error] if @card[:error]
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :find_product
  
  def checkout_session
    @processor = Payment::ProcessorService.new(params[:payment_strategy])
    response = @processor.process_payment(payment_options)

    raise "Something went wrong" unless response[:redirect_url]

    redirect_to response[:redirect_url], layout: false, allow_other_host: true
  rescue StandardError => e
    flash[:error] = e.message
    redirect_to product_path(@product)
  end

  def success
    flash[:success] = "Payment done successfully!"
    redirect_to products_path
  end

  def cancel
    flash[:error] = "Payment failed!"
    redirect_to products_path
  end


  def create
    payment_response = PaymentMethods::Stripe::PaymentService.call(:create_payment_intent, current_user.stripe_customer_id, @stripe_account_id, params[:card_id], @product.price)
    raise Errors::InvalidPaymentRequest, payment_response[:error] if payment_response[:error]
    
    confirm_payment_response = PaymentMethods::Stripe::PaymentService.call(:confirm_payment_intent, payment_response[:id], params[:card_id], redirect_url_after_payment)
    raise Errors::InvalidPaymentRequest, confirm_payment_response[:error] if confirm_payment_response[:error]
    
    puts  "#{confirm_payment_response.inspect}"

    flash[:success] = "Payment done successfully!"
    redirect_to confirm_payment_response[:next_action][:redirect_to_url][:url], layout: false, allow_other_host: true
  rescue Errors::InvalidPaymentRequest => e
    flash[:error] = e.message
    redirect_to product_path(@product)
  end



  private

  def find_product
    @product = Product.find(params[:product_id])
  end

  def payment_options
    { 
      product: @product, 
      success_url: success_product_payment_url(@product),
      cancel_url: cancel_product_payment_url(@product)
    }
  end

  def redirect_url_after_payment
    success_product_payment_url(@product)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :set_stripe_customer_id, only: :show

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
		response = PaymentMethods::Stripe::CardService.call(:card_list, @stripe_customer_id)
		if response[:error]
			flash[:error] = response[:error]
		else
			@cards = response[:data]
		end 

		@cards ||= []
	end

	private

	def set_stripe_customer_id
	    current_user.create_stripe_customer if current_user.stripe_customer_id.nil?
	    @stripe_customer_id = current_user.stripe_customer_id
	end
end

app/controllers/webhooks/payment_methods/stripes_controller.rb
module Webhooks
	module PaymentMethods
		class StripesController < ::ApplicationController
			skip_before_action :verify_authenticity_token

			def create
				payload = request.body.read
			    sig_header = request.env['HTTP_STRIPE_SIGNATURE']
			    webhook_secret = ENV['webhook_secret']

			    begin
			        @event = Stripe::Webhook.construct_event(
			            payload, sig_header, webhook_secret
			        )
			    rescue JSON::ParserError => e
			        # Invalid payload
			        return render_error(e)
			        
			    rescue Stripe::SignatureVerificationError => e
			        # Invalid signature
			        return render_error(e)
			    end

			    case @event.type
				when 'payment_intent.succeeded'
					create_payment_history('succeeded')
				when 'payment_intent.payment_failed'
					create_payment_history('failed')
				else
				  	return render_error(OpenStruct.new(message: "Event(#{@event.type}) not handled."))
				end

			    render json: { msg: 'Successfully Done' }, status: :ok
			end

			private

			def create_payment_history(status)
		        data = @event.data.object
		        PaymentHistory.create(application_fee: (data.application_fee_amount || 0), payment_intent_id: data.id, status: status, total_amount: data.amount, transfer_amount: data.amount_received, user_id: User.first.id)
	        end

			def render_error(error)
				render json: { msg: error.message }, status: 422
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/new.html.slim
.container
  	h1.text-center.m-4 Product List
	= form_tag cards_path, method: :post, local: true, data: {turbo: false} do

	    label.card-number Card Number
	    = text_field_tag :card_number, nil, class: 'form-control', value: '4242424242424242', required: true, maxlength: 16

	    label.expiry-month Expiry Date(month)
	    = text_field_tag :exp_month, nil, class: 'form-control', value: '11', required: true, minlength: 2, maxlength: 2

	    label.expiry-year Expiry Date(year)
	    = text_field_tag :exp_year, nil, class: 'form-control', value: '24', required: true, minlength: 2, maxlength: 2

	    label.cvc CVC
	    = text_field_tag :cvc, nil, class: 'form-control', value: '123', required: true, minlength: 3, maxlength: 3

	    = submit_tag 'Submit Payment', class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentGateway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class='<%="alert alert-#{type == 'success' ? 'success' : 'danger'}"%>'>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.slim
.container
  	h1.text-center.m-4 Product List
	.row.justify-content-center
	    - @products.each do |product|
		    .col-md-4
		        .card.mb-4
			        img.card-img-top(src="#{product.image_url}" alt="#{product.name}")
			        .card-body
			            h5.card-title = product.name
			            .d-flex.justify-content-between
			            	p.card-text
					            strong Price:
					            |  #{number_to_currency(product.price)}
			           		= link_to 'Buy', product_path(product), class: 'btn btn-primary px-4'

app/views/products/show.html.erb
<script type="importmap">
  { "imports": { "my_mod": "./show.js"} }
</script>

<script type="module">
    import { loadStripe } from "@stripe/stripe-js";
    const stripe = await loadStripe("pk_test_51OI4pKSA51MYk112tB65X12eEz8F58ufocjFqJ4TrQOBB5j6TDvIqe0pjd67YMjJafYRGQvcODjBijL6AAglRds800nQaOlryr");
    console.log('stripe', stripe)
    const elements = stripe.elements();

    const card = elements.create("card");
    card.mount("#card-element");

    card.addEventListener("change", function (event) {
      const displayError = document.getElementById("card-errors");
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = "";
      }
    });

    const form = document.getElementById("payment-form");
    form.addEventListener("submit", async function (event) {
      event.preventDefault();

      const { token, error } = await stripe.createToken(card);
      if (error) {
        const errorElement = document.getElementById("card-errors");
        errorElement.textContent = error.message;
      } else {

        console.log("=============token",token);
      }
    });

</script>


<%= form_tag product_payment_path(@product), method: 'post', id: 'payment-form' do %>
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element">
    </div>

    <div id="card-errors" role="alert"></div>
  </div>

  <button type="submit">Submit Payment</button>
<% end %>

app/views/products/show.html.slim
.container
  h1 Product Details

  .row
    .col-md-6
      img.img-fluid(src="#{@product.image_url}" alt="#{@product.name}")
    .col-md-6
      h2 = @product.name
      p = @product.description
      p
        strong Price:
        |  #{number_to_currency(@product.price)}

  hr

  h2 Payment

  br

  .row
    .col-md-6.p-4.border-end
      /= link_to 'Add New Card', new_cards_path, class: 'btn btn-info'

      = form_tag product_payment_path(@product), method: :post, local: true, data: {turbo: false} do
          label.fw-bold.pb-5 Choose Card:
          .row
            - if @cards.any?
              - @cards.each_with_index do |card, index|
                .form-check.col-md-4
                  input.form-check-input type="radio" name="card_id" id="card-#{index}" value="#{card.id}" required="required"
                  label.form-check-label for="card-#{index}"
                    .card.mb-4
                      .card-body
                        h5.card-title 
                          = card.brand
                          = link_to "-", "/cards/#{card.id}", data: {  turbo: true, turbo_method: :delete, confirm:  "Are you sure?"}
                        p.card-text = "**********" + card.last4
            - else 
              p.text-center 
                | No card added yet.
                      
          .d-flex.justify-content-around.pt-5
            = link_to 'Add New Card', "#{new_card_path}?return_url=#{request.path}", class: 'btn btn-info w-auto px-3 py-2'
            = submit_tag 'Submit Payment', class: 'btn btn-primary w-auto px-3 py-2', disabled: !@cards.any?

    .col-md-6.ps-5
      = form_tag checkout_session_product_payment_path(@product), method: :post, local: true, data: { turbo: false } do
        label.fw-bold.pb-5 Choose Payment Gateway:
        .form-check.col-12
          input.form-check-input type="radio" name="payment_strategy" id="payment_strategy_1" value="stripe" required="required"
          label.form-check-label for="payment_strategy_1"
            .card.mb-4
              .card-body
                h5.card-title Stripe
                p.card-text
                  | Pay securely with Stripe.

        .form-check.col-12
          input.form-check-input type="radio" name="payment_strategy" id="payment_strategy_2" value="paypal"
          label.form-check-label for="payment_strategy_2"
            .card.mb-4
              .card-body
                h5.card-title PayPal
                p.card-text
                  | Pay securely with PayPal.
        = submit_tag 'Submit Payment', class: 'btn btn-primary px-3 py-2 mt-5'